#!/bin/bash

INPUT=$(cat)
NCAT=$(command -v ncat nc | head -1)

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "$INPUT" | pbcopy
else
  if $NCAT --version &> /dev/null | grep "GNU" ; then
    echo "$INPUT" | $NCAT -c 127.0.0.1 52698
  else
    echo "$INPUT" | $NCAT 127.0.0.1 52698
  fi
fi

if [[ -n "$TMUX" ]]; then
  echo "$INPUT" | tmux load-buffer -
fi
