#!/bin/bash

INPUT=$(cat)

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "$INPUT" | pbcopy
else
  if nc --version &> /dev/null | grep "GNU" ; then
    echo "$INPUT" | nc -c 127.0.0.1 52698
  else
    echo "$INPUT" | nc 127.0.0.1 52698
  fi
fi

if [[ -n "$TMUX" ]]; then
  echo "$INPUT" | tmux load-buffer -
fi
