#!/bin/bash

# you can setup .watchman-files to be automatically created by watchman by
# running this:
#
#   watchman -- trigger . watchman-files -X '.hg*' '.watchman-files' -- watchman-files --force
#
# to stop, run this:
#
#   watchman trigger-del . watchman-files

if [ ! -f .watchmanconfig ]
then
  echo "This directory isn't tracked by Watchman"
  exit
fi

query() {
  WATCHMAN_QUERY='["query", ".", {
    "expression": ["allof",
    ["type", "f"],
    ["not", "empty"],
    ["not", ["suffix", "orig"]],
    ["not", ["dirname", ".hg", ["depth", "ge", 0]]],
    ["not", ["dirname", ".git", ["depth", "ge", 0]]]
    ],
    "fields": ["name"]
  }]'

  # TODO: get rid of the jq dependency to make this a little faster
  echo $WATCHMAN_QUERY | watchman -j | jq -r ".files[]"
}

if [ "$1" = "--force" ]
then
  query / > .watchman-files.new
  if [ -s .watchman-files.new ]
  then
    mv .watchman-files.new .watchman-files
  fi
  exit
fi

if [ -f .watchman-files ] && [ ! `find ".watchman-files" -mmin +15` ]
then
  cat .watchman-files
  exit
fi

query / | tee .watchman-files.new
if [ -s .watchman-files.new ]
then
  mv .watchman-files.new .watchman-files
fi
